language: csharp
solution: githubTestProject.sln
install:
  - nuget restore githubTestProject.sln
  - nuget install NUnit.Console -Version 3.0.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug githubTestProject.sln
  - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe ./githubTestProject.Web.Tests/bin/Debug/githubTestProject.Web.Tests.dll